### ISSUE TITLE
Bottlerocket Support

### ISSUE THREAD

**Issue by darylrobbins** [aws/efs-utils#146]
Any plans to support Bottlerocket?

**Comment by arnaldo2792** [comment]
Hello @darylrobbins. We have a [tracking issue] in the Bottlerocket repository to support encryption in EFS filesystems. Since efs-utils utility is written in python, it doesn't work out-of-the-box in Bottlerocket. We need to design how Bottlerocket will support this library without actually shipping python as part of the base image.

[tracking issue]: https://github.com/bottlerocket-os/bottlerocket/issues/1080

**Comment by RyanStan** [comment]
I'm going to close this issue since this is being tracked in the issue linked above.
