### ISSUE TITLE
Broken amazon-efs-mount-watchdog in v1.35.0: wrongly indented should_check_efs_utils_version

### ISSUE THREAD

**Issue by Phoosha** [aws/efs-utils#169]
The watchdog does not start at all anymore starting with v1.35.0 due to [this commit](https://github.com/aws/efs-utils/commit/3dd89caef058c744a419b6839416d726cdc5ab54). I'm getting the following error:
> AttributeError: type object 'EFSUtilsVersionChecker' has no attribute 'should_check_efs_utils_version'

This can be fixed by unindenting the method one level. Currently it's a child of the previous method instead of the class:
~~~python
    @staticmethod
    def check_if_using_old_version(current_version_string):
[...]
        @staticmethod
        def should_check_efs_utils_version(config):
            """Returns True if a customer has enabled the amazon-efs-utils version check,
~~~

**Comment by RyanStan** [comment]
Hi Phoosha, thanks for pointing this out. Something went wrong in our testing process for this not to be caught. This change hasn't been merged into a tag release yet and is not part of v1.35.0. Make sure you're pulling v1.35.0 and not master for the time being.

**Comment by RyanStan** [comment]
[A new commit has been pushed to master to fix this issue](https://github.com/aws/efs-utils/commit/62fde08f790a1ab50f25b81f85940bec6f4b92e9). We are reviewing our testing process to make sure that this does not happen again. However, we still recommend using the latest tagged release instead of our master.
