### ISSUE TITLE
amazon-efs-mount-watchdog in v1.35.0: wrongly indented should_check_efs_utils_version

### ISSUE THREAD

**Issue by dbalajis** [aws/efs-utils#190]
This is a follow-up of the issue: https://github.com/aws/efs-utils/issues/169 , We are still getting the same error in 1.35. Could you please fix the indentation in the next release? When i fixed the indendation, we are able to run the watchdog service.

`Nov 21 17:43:00  env: Traceback (most recent call last):
Nov 21 17:43:00 test-envenv: File "/usr/bin/amazon-efs-mount-watchdog", line 2386, in <module>
Nov 21 17:43:00 test-env env: main()
Nov 21 17:43:00 test-env env: File "/usr/bin/amazon-efs-mount-watchdog", line 2377, in main
Nov 21 17:43:00 test-env env: if EFSUtilsVersionChecker.should_check_efs_utils_version(config):
Nov 21 17:43:00 test-env env: AttributeError: type object 'EFSUtilsVersionChecker' has no attribute 'should_check_efs_utils_version'
Nov 21 17:43:00 test-env systemd: amazon-efs-mount-watchdog.service: main process exited, code=exited, status=1/FAILURE
Nov 21 17:43:00 test-env systemd: Unit amazon-efs-mount-watchdog.service entered failed state.
Nov 21 17:43:00 test-env systemd: amazon-efs-mount-watchdog.service failed.
Nov 21 17:43:15 test-env systemd: Stopped amazon-efs-mount-watchdog.
Nov 21 17:43:15 test-env systemd: Started amazon-efs-mount-watchdog.`

[ec2-user@test-env~]$ amazon-efs-mount-watchdog --version
/usr/bin/amazon-efs-mount-watchdog Version: 1.35.0

**Comment by RyanStan** [comment]
Hi, [this error was fixed by this commit](https://github.com/aws/efs-utils/commit/62fde08f790a1ab50f25b81f85940bec6f4b92e9). Both the error commit, and the commit with the fix, were pushed to the master branch, and were not included in the [v1.35.0 release](https://github.com/aws/efs-utils/tree/v1.35.0).

We recommend to build source from the latest tag release, instead of from master. The README on this project doesn't seem to call that out, so we will need to update it.

To check out the latest tag, you can run these commands
```
git clone https://github.com/aws/efs-utils.git
cd efs-utils
LATEST_TAG=$(git describe --tags --abbrev=0)
git checkout $LATEST_TAG
```
