### ISSUE TITLE
Not able to mount efs using efs mount helper on ec2-instance

### ISSUE THREAD

**Issue by ghost** [aws/efs-utils#21]
I have just created EFS and launched the ec2 instance in the same AZ and trying to mount EFS on EC2 instance using EFS mount helper.

Steps to regenerate error
1. Create EFS 
2. Launch EC2 instance in same AZ and share the same SG with EFS
3. sudo yum install -y amazon-efs-utils
4. sudo mkdir efs
5. sudo mount -t efs FILE_SYSTEM_ID:/ efs

Error Getting
```Failed to resolve "fs-xxxxxxx.efs.us-east-1.amazonaws.com" - check that your file system ID is correct.```

**Comment by darrylsosborne** [comment]
@mohitkumarsharmaflux7 Please verify that both DNS Resolution and DNS Hostnames are enabled for your VPC and your VPC is configured to use the DNS server provided by Amazon.

DNS hostnames - https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-viewing
DHCP option set - https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html

**Comment by mohitkumarsharmaflux7** [comment]
both DNS Resolution and DNS Hostnames are enabled for my VPC 
when I am trying to mount the EFS using NFS client then i am able to moun it.
but using efs mount helper i am not able to mount it.

this is working
`mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${EFS_HOST}:${EFS_LOCATION} ${MOUNT_LOCATION}`


this is not working
`mount -t efs  -o tls ${EFS_HOST}:${EFS_LOCATION} ${MOUNT_LOCATION}`

**Comment by volta1** [comment]
@mohitkumarsharmaflux7 are you using the same value for ${EFS_HOST} in each command?

For the first example with 'mount -t nfs4', ${EFS_HOST} should be a FQDN (i.e. fs-abdc1234.efs.us-east-1.amazon.com).
In the second example using the EFS mount helper, the parameter should only contain a file system ID, not a FQDN (i.e. fs-abcd1234).

If you're providing a FS ID while using the mount helper, can you try mounting manually using the DNS name that's printed in the error message?  Does that work?

**Comment by joetrav** [comment]
@mohitkumarsharmaflux7 are you using the same value for ${EFS_HOST} in each command?

For the first example with 'mount -t nfs4', ${EFS_HOST} should be a FQDN (i.e. fs-abdc1234.efs.us-east-1.amazon.com). 

In the second example using the EFS mount helper, the parameter should only contain a file system ID, not a FQDN (i.e. fs-abcd1234).

If you're providing a FS ID while using the mount helper, can you try mounting manually using the DNS name that's printed in the error message? Does that work?

**Comment by mohitkumarsharmaflux7** [comment]
@joetrav yes,using same EFS_HOST
I have already tried with all combinations
using ID, DNS name,FQDN
but giving error

when trying to mount using DNA name that is printed in error
$mount -t efs DNS:/ jit
The specified CNAME "DNS" did not resolve to a valid DNS name for an EFS mount target. Please refer to the EFS documentation for mounting with DNS names for examples: https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html

and when i am trying to 
$ nslookup DNS 
it is resolvable

**Comment by joetrav** [comment]
Sorry, I missed the part in your reply that said you were using your own DNS server.

The EFS mount helper requires you're using the Amazon-provided DNS at this time.

As a workaround, you can add a host entry (mapping your file system ID to the IP of a desired mount target) on your clients to use the mount helper with TLS.  There's an example detailed here: https://docs.aws.amazon.com/efs/latest/ug/efs-onpremises.html#wt5-step2-get-efs-utils

**Comment by mohitkumarsharmaflux7** [comment]
I tried the entry in /etc/hosts file , it worked for 
`IP  EFS_DNA_NAME`

but  I want to use my route53 domain to point it
I have a record like
MY_DOMAIN  pointing to mount targets IPs

but when I tried to use it 
as in /etc/hosts
`IP MY_ROUTE53_DNS`
and then I am not able to mount.

Another question is , why we need to add an entry in /etc/hosts , bec we are able to resolve the DNS name using nslookup.

**Comment by claco** [comment]
I might be able to shed light on this from another experience.

The instance DNS request -> DNS resolver must happen in the same AZ that the mount point resides, otherwise it will fail to resolve. This is presumably to keep folks from accidentally mounting an EFS across AZs. This drove me quite perplexed until I was told about resolution across AZ yields NXDOMAIN for mount points/fs ids.

This is using the new DNS naming convention. There also used to be an older one in 2016, but the efs-tools doesn't support it: https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html

In our case, we have a set of DNSMasq resolvers across multiple AZs. Depending on which AZ your ec2 instance hit, you would get a resolution, or an NXDOMAIN. In my case, the /etc/hosts option was also the only one that worked because the Route53 resolution again, could have originated proxied through and of the 3 DNSMasq servers we have. This is even more entertaining if you also have dnsmasq caching on your instances.

Frankly, I wish the efs-utils either supported the old dns naming convention, or always allowed me to specify the AZ of the mount point for the efs id.
