### ISSUE TITLE
Not able to mount with TLS from another region

### ISSUE THREAD

**Issue by santillaner** [aws/efs-utils#33]
Hi there, 

Following instructions to configure /etc/hosts, VPC peering, etc, I've been able to successfully mount from Paris to an EFS residing in Ireland issuing `sudo mount -t efs fs-fXXXXXXX:/ /efs `.

However when I add the TLS option, Stunnel fails:
```
[ec2-user@ip-X-X-X-X ~]$ sudo mount -t efs -o tls fs-fXXXXXXX:/ /efs
mount.nfs4: Connection reset by peer
Failed to initialize TLS tunnel for fs-fXXXXXXX
```

Is it possible to use TLS in EFS between Regions? 

Cheers

Manuel

**Comment by Josh-Fan** [comment]
Same problem here, EC2 in eu-west-2a cannot mount the EFS in eu-west-2c by TLS, the VPS peer works fine. Moreover, route table and security group have been checked, need a solution.

**Comment by Josh-Fan** [comment]
> Hi there,
> 
> Following instructions to configure /etc/hosts, VPC peering, etc, I've been able to successfully mount from Paris to an EFS residing in Ireland issuing `sudo mount -t efs fs-fXXXXXXX:/ /efs `.
> 
> However when I add the TLS option, Stunnel fails:
> 
> ```
> [ec2-user@ip-X-X-X-X ~]$ sudo mount -t efs -o tls fs-fXXXXXXX:/ /efs
> mount.nfs4: Connection reset by peer
> Failed to initialize TLS tunnel for fs-fXXXXXXX
> ```
> 
> Is it possible to use TLS in EFS between Regions?
> 
> Cheers
> 
> Manuel

OK, I find one solution, I add VPC itself as the destination in security group outbound rules, and it works.

**Comment by santillaner** [comment]
Hi @Josh-Fan, 

You succeded in connecting 2 AZ's in same region, didn't you? I've been trying your solution, and it works for different AZ's on same region, but not for cross-region TLS. 

Found no doc in AWS as to how-to resolve this for EFS with TLS cross-region.

**Comment by Josh-Fan** [comment]
> Hi @Josh-Fan,
> 
> You succeded in connecting 2 AZ's in same region, didn't you? I've been trying your solution, and it works for different AZ's on same region, but not for cross-region TLS.
> 
> Found no doc in AWS as to how-to resolve this for EFS with TLS cross-region.

Sorry, I missed some of your word. Yes, I have only tried in same region (London), but not in different regions. There might some problems existing in AWS EFS mount helper, I think.

**Comment by lilferna** [comment]
Thanks for the feedback. EFS will take a look and post a more detailed response.

**Comment by joetrav** [comment]
Hi folks, thanks for the feedback.  It seems like our [documentation](https://docs.aws.amazon.com/efs/latest/ug/manage-fs-access-vpc-peering.html) may be unclear in this area, so we'll address that.  In short, we're not able to reproduce the issue, and we can successfully mount EFS file systems using TLS across AWS regions with VPC peering.  

Here are the steps we followed to successfully mount an EFS file system using TLS across regions.  Let's say we have an EC2 instance in region A, mounting an EFS file system in region B:

- In following the steps in [Creating and Accepting a VPC Peering connection](https://docs.aws.amazon.com/vpc/latest/peering/create-vpc-peering-connection.html), you can create a peering connection in region B and accept the connection in region A.

- Next, follow [Updating Your Route Tables for a VPC Peering Connection](https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-routing.html) to ensure that in region A's route table, the CIDR block for the subnet in region B is included, and vice-versa.

- In [Updating your Security Groups to Reference Peer VPC Groups](https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-security-groups.html), you'll add the following inbound security group rule to region B: TYPE=NFS, PROTOCOL=TCP, PORT RANGE=2049, SOURCE=<EC2-CIDR>

- Follow the steps in [Before You Begin](https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-prepare), [Step 1: Setting Up Your EC2 Instance](https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-step1-efs), and [Step 2: Mount the EFS File System](https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-step2-mount-file-system) to test if the VPC peering connection is properly configured.

- Last, by following the steps in [Encrypting Data In Transit](https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-step3-get-efs-utils), update your /etc/hosts file and efs-utils.conf to specify your file system ID and region, and you should be good to go.

`sudo mount -t efs -o tls fs-12345678 ~/efs`

If these steps aren't working for you, please share how you're trying to set up and access EFS across regions (i.e. using VPC peering or otherwise) and what commands you're executing to mount the file system.  If you're still having trouble, it would also help if you could enable stunnel logging and share the output with us:

- Open /etc/amazon/efs/efs-utils.conf for editing

- Set logging_level = DEBUG and stunnel_debug_enabled = true

- Share the logs with us: /var/log/amazon/efs/fs-*.stunnel.log

Thanks,
--Joe
Amazon EFS team

**Comment by santillaner** [comment]
Thanks a bunch @joetrav , that did it for me!

The missing step for me was to change the efs-utils.conf so that the other region was resolved. 

I close this issue. 

Cheers!

Manuel
