### ISSUE TITLE
Document argument pass-through to mount.nfs

### ISSUE THREAD

**Issue by JamieGruener** [aws/efs-utils#34]
NFS supports these options so it seems natural that EFS-Utils should also support these options. Is there a reason why it doesn't?

--Jamie

**Comment by maxbecke** [comment]
Thanks for the feedback! This is the first request we've had for this functionality, and we're happy to have the feature request.

**Comment by maxbecke** [comment]
Hi @JamieGruener, I have another update for you. The [`mount.efs` script will pass-through](https://github.com/aws/efs-utils/blob/master/src/mount_efs/__init__.py#L513) arguments passed with `-o` to the `mount.nfs` call. The man page does not mention this, so I'm going to change up the title again to track updating the man page.

This example here shows how to override the NFS version, and shows that the NFS client has negotiated 4.0 instead of the default 4.1:

```
$ sudo mount -t efs -o nfsvers=4.0 FS_ID:/ /mnt/efs
$ mount -v | grep /mnt/efs
FS_ID.efs.us-east-1.amazonaws.com:/ on /mnt/efs type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=CLIENT_IP,local_lock=none,addr=EFS_IP)
```

**Comment by JamieGruener** [comment]
Thanks for looking into it. The problem we were trying to tackle was mounting the EFS volume as a specific user, root in this case. Totally missed the fact that NFS doesn't support `uid` or `gid` as options.

**Comment by geertj** [comment]
@JamieGruener I'm one of the product managers with Amazon EFS and I'd be interested learn more about your use case. Feel free to drop me a line on gerardu at amazon dot com if you'd like.

**Comment by RyanStan** [comment]
By mounting an access point, you can assume the uid and gid configured for the access point.

[Working with Amazon EFS access points](https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html)
