### ISSUE TITLE
How to install amazon-ecs-volume-plugin on RHEL7

### ISSUE THREAD

**Issue by jeremietharaud** [aws/efs-utils#78]
Hi guys,

I'm trying to install the EFS capability on a custom AMI based on Redhat (7.8) but after having installed the efs-utils as rpm package by following this [documentation](https://docs.aws.amazon.com/efs/latest/ug/installing-other-distro.html), I'm stucked because I don't know how to install the amazon-ecs-volume-plugin. 
The efs-utils package does not install the amazon-ecs-volume-plugin.service in systemd unlike an amazon Linux 2 AMI.

Can someone help me to install it ?

Thank you.
Jeremie Tharaud

**Comment by Cappuccinuo** [comment]
Hey @jeremietharaud ,

`amazon-ecs-volume-plugin` should be a feature since ecs-init 1.38.0, installing ecs-agent should give you the ability to use this plugin.

To install ecs-init on your RHEL7 instance, you can follow https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-nonamazonlinux. 

If you encounter further issue during the installation, https://github.com/aws/amazon-ecs-init/issues should be the best place to find the solution.

Thanks.

**Comment by jeremietharaud** [comment]
OK I will check with ecs-unit then.
