### ISSUE TITLE
Feature Request: Ability to mount with CNAME instead of fs_id

### ISSUE THREAD

**Issue by dinakar29** [aws/efs-utils#9]
Hello,

Could this be a feature request? We want to be able to mount the EFS volume with the Route 53 CNAME of the EFS volume instead of the filesystem ID.

Thanks!

**Comment by lilferna** [comment]
Thanks for the feedback. We’ll have someone take a look and post a more detailed response once we better understand the issue.

**Comment by joetrav** [comment]
Dinakar,
EFS product manager here.  Are you able to share more information on your use case for using the full CNAME as opposed to the file system ID?  If you're not comfortable sharing this information publicly, please let us know and we'll find a way to connect in a private channel.

**Comment by dinakar29** [comment]
Hi @joetrav,

Thanks for the prompt response! I'll be happy to share our use case privately. How would I go about doing that?

Thanks!

**Comment by joetrav** [comment]
Send me an email - <my github user name> at amazon

**Comment by atomray** [comment]
Hi! I'm just trying out these utils - thanks for them - we use the FQDN for EFS because we tie together on-prem ActiveDirectory and Route 53 and EFS. Works for NFS but when I used EFS I get "Invalid file system name" with the fully qualified name. Found this issue and thought I'd add my use case.

**Comment by pitkley** [comment]
Just to bump this up a bit: I am currently encountering the same limitation. Our use-case is as follows:

* We build static AMIs that contain our applications.
* The applications require an EFS to be mounted.
* The applications auto-start with system startup, which means EFS has to be available first.
* We do not know the EFS-ID at build-time, since it changes across environments/deployments.
* What we _do_ know is a static DNS-CNAME-record which we keep in a private hosted zone per environment, which maps to the EFS-DNS-name.

I am interested in contributing this change, but want to make sure first that there is no work done for this on your side yet? /cc @joetrav

**Comment by maxbecke** [comment]
pitkley,

Thanks for the feedback.  We are not actively working on this functionality. We would be happy to review your contribution if you submit a pull request.
