### ISSUE TITLE
mount -t efs default to IMDSv1

### ISSUE THREAD

**Issue by chenwany** [aws/efs-utils#91]
Hi team.
It seems that `mount -t efs` default to IMDSv1, and it will use IMDSv2 when IMDSv1 fails. What about making it default to IMDSv2 and fall back to IMDSv1 if IMDSv2 not work? 

I am asking because our product is using `mount -t efs` and we are in transition to IMDSv2. We don't want to disable IMDSv1 in our product to block our users who use IMDSv1, but we want to make it safer and reliable by default to IMDSv2 and fall back to IMDSv1, so IMDSv1 calls can be reduced.

Is it possible to make `mount -t efs` firstly try IMDSv2, then fall back to IMDSv1 if it doesn't work?
Thanks!

**Comment by Cappuccinuo** [comment]
Hey @chenwany , thanks for the feedback! We'll have someone to take a look

**Comment by Cappuccinuo** [comment]
The efs-utils is now updated to use IMDSv2 by default and fallback to use IMDSv1 if the token fetch failed due to timeout.

There are certain case that won't work in this case of the IMDSv1 fallback, e.g. Sagemaker instance. We will release a fix in v1.31.2 for this case, and customer can update the config follow [this part](https://github.com/aws/efs-utils#the-way-to-access-instance-metadata) to disable the token fetch for now.
